Catch bucket creation failures

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,7 +14,7 @@ jobs:
       - name: "Set up Cloud SDK"
         uses: "google-github-actions/setup-gcloud@v2"
       - name: "Create CloudStorage Bucket"
-        run: "gcloud storage buckets create gs://${{ github.event.repository.name }}"
+        run: 'gcloud storage buckets create gs://${{ github.event.repository.name }} || echo "TBD: Catch error"'
   open_tofu_deploy:
     runs-on: ubuntu-latest
     needs: create_tf_state
